server:
  port: 8090
mybatis:
  type-aliases-package: com.example.demo.bean
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:SqlMapConfig.xml
  
    
  
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.11:3306/vue?characterEncoding=utf8
        username: root
        password: 'r4t5#$%y6u7'
        type: org.apache.commons.dbcp.BasicDataSource
        dbcp2: 
          max-total: 20
          
logging:
    level:
      com.example.demo.mapper: DEBUG   
     
      
    
   
